### PR TITLE
Add Bleve

### PR DESCRIPTION
**Pull request by mosuka**
Add Bleve as a benchmark target.

### CODE REVIEW

**Comment by fulmicoton** [comment]
After indexing seems successful (around 25 mn and 11 GB later), when I try to run `make serve` I am getting an error.

The only output is 
`ERROR`

Is there a env variable to get logs or something like that?

**Comment by mosuka** [comment]
Please wait for a while. I'll check it.

**Comment by mosuka** [comment]
@fulmicoton 
The reason is that do_query.go didn’t register the same analyzer as build_index.go at initialization.
I Added the same analyzer to do_query.go.
Please retry it. Sorry for the inconvenience.

**Comment by fulmicoton** [comment]
It works! Awesome! Thank you!

**Pull request merged**
